name: Run tests

on: [pull_request]

jobs:
  publish:
    name: Install and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_CLI_TOKEN }}
      - run: yarn install
      - run: yarn test
      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          eslint: true # needs to fix ESLint errors
          prettier: true # Prettier causes unknown issues with current files
      # Restore react-native metro cache for speed-up publish time
      # See: https://github.com/facebook/metro/blob/7dca99af2e2af17921aa4a1e16b1972adc0d11e4/packages/metro-config/src/defaults/index.js#L121-L125
      - name: Find Metro cache
        id: metro-cache-dir-path
        uses: actions/github-script@v4
        with:
          result-encoding: string
          script: |
            const os = require('os');
            const path = require('path');
            return path.join(os.tmpdir(), 'metro-cache');
      - name: Restore Metro cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.metro-cache-dir-path.outputs.result }}
          key: ${{ runner.os }}-metro-cache-${{ matrix.app }}-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-metro-cache-${{ matrix.app }}-${{ github.base_ref }}
            ${{ runner.os }}-metro-cache-${{ matrix.app }}-
      - run: expo publish --release-channel=pr-${{ github.event.number }}
        env:
          NODE_OPTIONS: --max_old_space_size=8192
      - run: echo 'App PR link is https://expo.dev/@smarttenants/smartTenant?release-channel=pr-${{ github.event.number }}'
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.19.0
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          channel-id: "C03JH7NEKRR"
          # For posting a simple plain text message
          slack-message: "New Pull Request activity :red_circle: \n <${{ github.event.pull_request.html_url || github.event.head_commit.url }}|*${{ github.event.pull_request.title }}*>\n Description: ${{ github.event.pull_request.body }} \n Test the Pull Request application here: https://expo.dev/@smarttenants/smartTenant?release-channel=pr-${{ github.event.number }} :strong:"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      - uses: mshick/add-pr-comment@v1
        with:
          message: |
            App PR link is https://expo.dev/@smarttenants/smartTenant?release-channel=pr-${{ github.event.number }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: "github-actions[bot]" # The user.login for temporary GitHub tokens
          allow-repeats: false # This is the default
